In [1]:
import numpy as np
from scipy.stats import skew, kurtosis

### Basic Array Creation

# Creatation of List
How to create Lists in python?

In [2]:
# Create Lists in Python Without Using np
a = [1,2,3,4]
print(a)

# Create Lists in Python Without Using np
a = np.array((1,2,3,4))
a

[1, 2, 3, 4]


array([1, 2, 3, 4])

# Type
Accuire type of list in python.

In [3]:
a.dtype

dtype('int64')

# Creatation of Arrays
1.SIMPLE ARRAY CREATION

2.CHECKING THE TYPE

3.NUMERIC "TYPE" OF ELEMENTS OF ARRAYS

4.Array dim

5.Array Shape

6.BYTES PER ELEMENT

7.BYTES OF MEMORY USED, How many bytes for one array element

8.Total bytes in an Array

In [5]:
# Int array
# 1. SIMPLE ARRAY CREATION
a = np.array((1,2,3,4,5))
# 2. CHECKING THE TYPE
b = type(a)
# 3. NUMERIC "TYPE" OF ELEMENTS OF ARRAYS
c = a.dtype
# 4.Array dim
d = a.ndim
# 5.Array Shape
e = a.shape
# 6.BYTES PER ELEMENT
f = a.itemsize
# 7.BYTES OF MEMORY USED, How many bytes for one array element
g = a.nbytes
# 8.Total bytes in an Array
h = a.size * a.itemsize

#Print All Values 
a,b,c,d,e,f,g,h

(array([1, 2, 3, 4, 5]), numpy.ndarray, dtype('int64'), 1, (5,), 8, 40, 40)

In [6]:
# Decimal array
# 1. SIMPLE ARRAY CREATION
a = np.array((1.5,2.2,3.3,4.4,5.5))
# 2. CHECKING THE TYPE
b = type(a)
# 3. NUMERIC "TYPE" OF ELEMENTS OF ARRAYS
c = a.dtype
# 4.Array dim
d = a.ndim
# 5.Array Shape
e = a.shape
# 6.BYTES PER ELEMENT
f = a.itemsize
# 7.BYTES OF MEMORY USED, How many bytes for one array element
g = a.nbytes
# 8.Total bytes in an Array
h = a.size * a.itemsize

#Print All Values 
a,b,c,d,e,f,g,h

(array([1.5, 2.2, 3.3, 4.4, 5.5]),
 numpy.ndarray,
 dtype('float64'),
 1,
 (5,),
 8,
 40,
 40)

9.Try to assign a float into an int32

10.Use .fill function # fill has the same behavior


In [7]:
# 9.Try to assign a float into an int32
a = np.array((1,2,3,4,5,6)).astype("int32")
a[:] = 14.6
a

array([14, 14, 14, 14, 14, 14], dtype=int32)

In [8]:
# 10.Use .fill function # fill has the same behavior
a.fill(2.4)
a

array([2, 2, 2, 2, 2, 2], dtype=int32)

11.Add two  arrays

12.Multiple both arrays

13.Use ** operator in array operation

14.Create array from 0.0 to 11.0

15.Multiply entire array with a scalar value
 c = (2.0 * np.pi)

16.Use np.arrange function tocreate an array with step of from 1.0 to 3.0

In [9]:
# 11.Add two  arrays
a = np.array((1,2,3,4))
b = np.array((5,6,7,8))
c = a + b
c


array([ 6,  8, 10, 12])

In [10]:
# 12.Multiple both arrays
a = np.array((1,2,3,4))
b = np.array((5,6,7,8))
c = a * b
c


array([ 5, 12, 21, 32])

In [11]:
# 13.Use ** operator in array operation
a = np.array((1,2,3,4))
b = np.array((5,6,7,8))
c = a ** b
c


array([    1,    64,  2187, 65536])

In [12]:
# 14.Create array from 0.0 to 11.0
a = np.arange(0.0,11.0)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
# 15.Multiply entire array with a scalar value
b = np.array((1,2,3,4))
c = (2.0 * np.pi)
d = b * c
d

array([ 6.28318531, 12.56637061, 18.84955592, 25.13274123])

In [14]:
# 16.Use np.arrange function to create an array with step of from 1.0 to 3.0
a = np.arange(1.0,3.0,0.5)
a

array([1. , 1.5, 2. , 2.5])

# Slicing
var[lower:upper:step]
• Extracts a portion of a sequence by specifying a lower and upper bound.

• The lower-bound element is included, but the upper-bound element is not included.

• Mathematically: [lower, upper). The step value specifies the stride between elements.

1. Etract array indices from 1 to 3:
2. Use negative indices as well
3. Omitted boundaries are assumed to be the beginning (or end) of the array grab first three elements
4. Grab last two elements
5. Grab every other element
6. slicing the last two elements returns the data there
7. Can we insert an iterable of length two? or a scalar value
8.Arrays created by slicing share data with the originating array. Changing values in a slice also changes the original array.
For example create a slice containing two elements of a changing b changed a! Have an experiment
9. if an array a = [[0, 1, 2, 3, 4],[1, 2, 3, 4, 5]] extract values from row 3 to onward and from col 0, 2 and 5
10. Perform some masking on a = np.arange(0,36).reshape(6,6)
with mask = np.array([1, 0, 1, 0, 0, 1])


In [15]:
# 1. Etract array indices from 1 to 3:
a = np.arange(1,11)
a[1:4]

array([2, 3, 4])

In [16]:
# 2. Use negative indices as well
a = np.arange(1,11)
a[-3:]

array([ 8,  9, 10])

In [17]:
# 3. Omitted boundaries are assumed to be the beginning (or end) of the array grab first three elements
a = np.arange(1,11)
a[:3]

array([1, 2, 3])

In [18]:
# 4. Grab last two elements
a = np.arange(1,11)
a[-2:]

array([ 9, 10])

In [19]:
# 5. Grab every other element
a = np.arange(1,11)
a[::2]

array([1, 3, 5, 7, 9])

In [20]:
# 6. slicing the last two elements returns the data there
a = np.arange(1,11)
a[-2:]


array([ 9, 10])

In [21]:
# 7. Can we insert an iterable of length two? or a scalar value
a = np.arange(1,11)
a[[1,2]]

array([2, 3])

In [22]:
# 8.Arrays created by slicing share data with the originating array. Changing values in a slice also changes the original array.
# For example create a slice containing two elements of a changing b changed a! Have an experiment
a = np.arange(1,11)
b = a[1:3]
b[0] = 100
a

array([  1, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [25]:
# 2D-Array Slicing
a[-2:-1,2:4]
# arr[start_row:end_row, start_col:end_col]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [26]:
# 3D-Array Slicing
threeD = np.array(range(1, 49)).reshape(3, 4, 4)
print(threeD)
threeD[:,1:3,1:3]

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]]


array([[[ 6,  7],
        [10, 11]],

       [[22, 23],
        [26, 27]],

       [[38, 39],
        [42, 43]]])

In [27]:
# 9. if an array a = [[0, 1, 2, 3, 4],[1, 2, 3, 4, 5]] extract values from row 3 to onward and from col 0, 2 and 5
a = np.arange(0,36).reshape(6,6)
print(a)
print(a[2:,[0,5,2]])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[12 17 14]
 [18 23 20]
 [24 29 26]
 [30 35 32]]


In [28]:
# 10. Perform some masking on a = np.arange(0,36).reshape(6,6)
# with mask = np.array([1, 0, 1, 0, 0, 1])
a = np.arange(0,36).reshape(6,6)
mask = np.array([1, 0, 1, 0, 0, 1])
print(a)
# print(a[mask])
# a[[1,0,1,0,0,1]]

a[[[True, False, True, False, False, True],
[True, False, True, False, False, True],
[True, False, True, False, False, True],
[True, False, True, False, False, True],
[True, False, True, False, True, True],
[True, False, True, False, False, True]]]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([ 0,  2,  5,  6,  8, 11, 12, 14, 17, 18, 20, 23, 24, 26, 28, 29, 30,
       32, 35])

# Array Functions
1.Arange([start,] stop[, step],dtype=None)
Nearly identical to Python’s range(). Creates an array of values in the range [start,stop) with the specified step value. Allows non-integer values for start, stop, and step. Default dtype is derived from the start, stop, and step values. create an array with arange.

2.Create arrays with ONES, ZEROS, shape is a number or sequence specifying the dimensions of the array. If dtype is not specified, it defaults to float64.

3.Generate an n by n identity array. The default dtype is float64.

4.use empty, full, and fill, max, min, std, mean, var, argmax, linspace

5.

  Rule 1:
  Operations between multiple array objects are first checked for proper shape match.

  Rule 2:
  Mathematical operators (+ - * / exp, log, ...) apply element by element, on the values.

  Rule 3:
  Reduction operations (mean, std, skew, kurt, sum, prod, ...) apply to the whole array, unless an axis is specified.

  Rule 4:
  Missing values propagate unless explicitly ignored (nanmean, nansum, ...).

6.
Create the array below with
                  a = np.arange(-15, 15).reshape(5, 6) ** 2
1. The maximum of each row
2. The mean of each column
3. The position of the overall minimum


In [29]:
# 1.Arange([start,] stop[, step],dtype=None)
# Nearly identical to Python’s range(). Creates an array of values in the range [start,stop) with the specified step value.
# Allows non-integer values for start, stop, and step. Default dtype is derived from the start, stop, and step values. create an array with arange.

a = np.arange(1, 10.1, 2)
a

array([1., 3., 5., 7., 9.])

In [30]:
# 2.Create arrays with ONES, ZEROS, shape is a number or sequence specifying the dimensions of the array. If dtype is not specified, it defaults to float64.
shape = (3, 4)  # Specify the shape of the array
ones_array = np.ones(shape)
zeros_array = np.zeros(shape)

print("Ones Array:")
print(ones_array)

print("\nZeros Array:")
print(zeros_array)

Ones Array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Zeros Array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [31]:
# 3.Generate an n by n identity array. The default dtype is float64.
n = 4
identity_array = np.identity(n)
print("Ones Array: \n\n", identity_array)
# print(identity_array)

Ones Array: 

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [32]:
# 4.use empty, full, and fill, max, min, std, mean, var, argmax, linspace
# Empty
empty_array = np.empty((2, 2))
print("Empty Array: \n\n", empty_array)

# Full
full_array = np.full((2, 2), 7)
print("\nFull Array: \n\n", full_array)

# Fill
fill_array = np.full((2, 2), 7)
fill_array.fill(5)
print("\nFill Array: \n\n", fill_array)

# Max
max_array = np.array([1, 5, 3, 4])
max_value = np.max(max_array)
print("\nMax Value: ", max_value)

# Min
min_array = np.array([1, 5, 3, 4])
min_value = np.min(min_array)
print("\nMin Value: ", min_value)

# Std
std_array = np.array([1, 5, 3, 4])
std_value = np.std(std_array)
print("\nStd Value: ", std_value)

# Mean
mean_array = np.array([1, 5, 3, 4])
mean_value = np.mean(mean_array)
print("\nMean Value: ", mean_value)

# Var
var_array = np.array([1, 5, 3, 4])
var_value = np.var(var_array)
print("\nVar Value: ", var_value)

# Argmax
argmax_array = np.array([1, 5, 10, 4])
argmax_value = np.argmax(argmax_array)
print("\nArgmax Value: ", argmax_value)

# Linspace
linspace_array = np.linspace(1, 10, 5)
print("\nLinspace Array: ", linspace_array)

Empty Array: 

 [[1. 1.]
 [1. 1.]]

Full Array: 

 [[7 7]
 [7 7]]

Fill Array: 

 [[5 5]
 [5 5]]

Max Value:  5

Min Value:  1

Std Value:  1.479019945774904

Mean Value:  3.25

Var Value:  2.1875

Argmax Value:  2

Linspace Array:  [ 1.    3.25  5.5   7.75 10.  ]


In [33]:
arra = np.arange(1,11,2.25)
arra

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [34]:
# 5.

  # Rule 1:
  # Operations between multiple array objects are first checked for proper shape match.

array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

array3 = np


In [35]:
  # Rule 2:
  # Mathematical operators (+ - * / exp, log, ...) apply element by element, on the values.

array_addition = array1 + array2
array_subtraction = array1 - array2
array_multiplication = array1 * array2
array_division = array1 / array2

    # Mathematical Operations (log,exp)

result_exp = np.exp(array1)
result_log = np.log(array2)

print("\nArray Addition:\n\n", array_addition)
print("\nArray Subtraction:\n\n", array_subtraction)
print("\nArray Multiplication:\n\n", array_multiplication)
print("\nArray Division:\n\n", array_division)
print("\nArray Exponential:\n\n", result_exp)
print("\nArray Logarithm:\n\n", result_log)


Array Addition:

 [[ 8 10 12]
 [14 16 18]]

Array Subtraction:

 [[-6 -6 -6]
 [-6 -6 -6]]

Array Multiplication:

 [[ 7 16 27]
 [40 55 72]]

Array Division:

 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]

Array Exponential:

 [[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]

Array Logarithm:

 [[1.94591015 2.07944154 2.19722458]
 [2.30258509 2.39789527 2.48490665]]


In [36]:

# Rule 3:
  # Reduction operations (mean, std, skew, kurt, sum, prod, ...) apply to the whole array, unless an axis is specified.

  # Reduction Operations
array_mean = np.mean(array1)
array_std = np.std(array2)
array_skew = skew(array1, axis = 0)
array_kurt = kurtosis(array2)
array_sum = np.sum(array1)
array_prod = np.prod(array2)
array_concatenate = np.concatenate((array1, array2), axis=0)
array_split = np.split(array1, 2)

print("\nArray Mean:", array_mean)
print("\nArray Standard Deviation:", array_std)
print("\nArray Skew:", array_skew)
print("\nArray Kurtosis:", array_kurt)
print("\nArray Sum:", array_sum)
print("\nArray Product:", array_prod)
print("\nArray Concatenation:\n\n", array_concatenate)
print("\nArray Splitting:\n\n", array_split)



Array Mean: 3.5

Array Standard Deviation: 1.707825127659933

Array Skew: [0. 0. 0.]

Array Kurtosis: [-2. -2. -2.]

Array Sum: 21

Array Product: 665280

Array Concatenation:

 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Array Splitting:

 [array([[1, 2, 3]]), array([[4, 5, 6]])]


In [37]:
# Rule 4:
# Missing values propagate unless explicitly ignored (nanmean, nansum, ...).

# Define an array with NaN values
array_with_nan = np.array([[1, 2, np.nan],
                            [4, np.nan, 6]])

# Calculate mean and sum, ignoring NaN values
mean_without_nan = np.nanmean(array_with_nan)
sum_without_nan = np.nansum(array_with_nan)

print("Array with NaN values:")
print(array_with_nan)

print("\nMean (ignoring NaN values):", mean_without_nan)
print("Sum (ignoring NaN values):", sum_without_nan)


Array with NaN values:
[[ 1.  2. nan]
 [ 4. nan  6.]]

Mean (ignoring NaN values): 3.25
Sum (ignoring NaN values): 13.0


In [38]:
# Create the array below with
#                   a = np.arange(-15, 15).reshape(5, 6) ** 2
# 1. The maximum of each row
# 2. The mean of each column
# 3. The position of the overall minimum


a = np.arange(-15, 15).reshape(5, 6) ** 2
print(a)
# Task 1: Maximum of each row
max_of_each_row = np.max(a, axis=1)
print("Maximum of each row:", max_of_each_row)

# Task 2: Mean of each column
mean_of_each_column = np.mean(a, axis=0)
print("\nMean of each column :", mean_of_each_column)

# Task 3: Position of the overall minimum
min_position = np.unravel_index(np.argmin(a), a.shape)
print("\nPosition of the overall minimum :" , min_position)

[[225 196 169 144 121 100]
 [ 81  64  49  36  25  16]
 [  9   4   1   0   1   4]
 [  9  16  25  36  49  64]
 [ 81 100 121 144 169 196]]
Maximum of each row: [225  81   9  64 196]

Mean of each column : [81. 76. 73. 72. 73. 76.]

Position of the overall minimum : (2, 3)


### Zip Operations on Numpy Arrays
Use a zip function on two arrys.

Create another array which would be the sum of corresponding elements of two arrays using for loop.

In [39]:
array_a = [1, 2, 3, 4]
array_b = [2, 3, 4, 5]

# Answer Here
zipped_arrays = zip(array_a, array_b)
zipped_list = list(zipped_arrays)
print('Zipped Arrays :',zipped_list)

Zipped Arrays : [(1, 2), (2, 3), (3, 4), (4, 5)]


In [40]:
#For loop to add corresponding elements in two lists

# Answer Here
# Initialize an empty list to store the sum of corresponding elements
sum_array = []

# Iterate through the arrays and calculate the sum of corresponding elements
for elem1, elem2 in zip(array_a, array_b):
    sum_array.append(elem1 + elem2)

# Convert the list to a NumPy array
sum_array = np.array(sum_array)

print("Sum of Corresponding Elements:")
print(sum_array)


Sum of Corresponding Elements:
[3 5 7 9]


# Array Broadcasting
NumPy arrays of different dimensionality can be combined in the same expression. Arrays with smaller dimension are broadcasted to match the larger arrays, without copying data.

Broadcasting has two rules.
RULE 1: PREPEND ONES TO SMALLER ARRAY'S SHAPE
RULE 2: DIMENSIONS OF SIZE 1 ARE REPEATED WITHOUT COPYING


In [41]:
# Answer Here
# Broadcasting has two rules.
# RULE 1: PREPEND ONES TO SMALLER ARRAY'S SHAPE
# RULE 2: DIMENSIONS OF SIZE 1 ARE REPEATED WITHOUT COPYING

print("RULE 1: PREPEND ONES TO SMALLER ARRAY'S SHAPE")
a = np.ones((3, 5)) # a.shape == (3, 5)
b = np.ones((5,)) # b.shape == (5,)
reshaped_array_choice1 = b.reshape(1, 5) # result is a (1,5)-shaped array
reshaped_array_choice2 = b[np.newaxis, :]  # equivalent, more concise

print('\n Reshaped Array :',reshaped_array_choice1)
print('\n Reshaped Array :',reshaped_array_choice2)

print("\nRULE 2: DIMENSIONS OF SIZE 1 ARE REPEATED WITHOUT COPYING")

c = a + b # c.shape == (3, 5)
# is logically equivalent to...
tmp_b = b.reshape(1, 5)
tmp_b_repeat = tmp_b.repeat(3, axis=0)
c = a + tmp_b_repeat

print('\n Reshaped Array :\n',c)

RULE 1: PREPEND ONES TO SMALLER ARRAY'S SHAPE

 Reshaped Array : [[1. 1. 1. 1. 1.]]

 Reshaped Array : [[1. 1. 1. 1. 1.]]

RULE 2: DIMENSIONS OF SIZE 1 ARE REPEATED WITHOUT COPYING

 Reshaped Array :
 [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


1.Use reduce() operation on an array to reduec it into a single meaningful value. You. can also use a specific axis to apply reduce operation.

2.accumulate() creates a new array containing the intermediate results of the reduce operation at each element in a.


In [42]:
# 1.Use reduce() operation on an array to reduec it into a single meaningful value. You. can also use a specific axis to apply reduce operation.

print("Reduce Operation \n ")
a = np.array([1,2,3,4])
b = np.add.reduce(a)
print('Reduced Operation : ',b)

#       --------------------------------------------------

print('\n " STRING LIST EXAMPLE "')
string = np.array(['ab','cd','ef'], dtype='object')
string_reduce = np.add.reduce(string)
print('\n String Reduced : ', string_reduce)

#       --------------------------------------------------------

print('\n " LOGICAL OP EXAMPLES "')
LOGICAL_OP_Reduce = np.array([1,1,0,1])
Reduce_AND_Operator = np.logical_and.reduce(LOGICAL_OP_Reduce)
print('\n Reduce using AND Operator :',Reduce_AND_Operator)
Reduce_OR_Operator = np.logical_or.reduce(LOGICAL_OP_Reduce)
print('\n Reduce using OR Operator :',Reduce_OR_Operator)

Reduce Operation 
 
Reduced Operation :  10

 " STRING LIST EXAMPLE "

 String Reduced :  abcdef

 " LOGICAL OP EXAMPLES "

 Reduce using AND Operator : False

 Reduce using OR Operator : True


In [43]:
# 2.accumulate() creates a new array containing the intermediate results of the reduce operation at each element in a.

print("Accumulate Operation \n ")
a = np.array([1,2,3,4])
b = np.add.accumulate(a)
print('Accumulate Operation : ',b)

#       --------------------------------------------------

print('\n " STRING LIST EXAMPLE "')
string = np.array(['ab','cd','ef'], dtype='object')
string_accumulate = np.add.accumulate(string)
print('\n String Accumulate : ', string_reduce)

#       --------------------------------------------------------

print('\n " LOGICAL OP EXAMPLES "')
LOGICAL_OP_Accumulate = np.array([1,1,0])
Accumulate_AND_Operator = np.logical_and.accumulate(LOGICAL_OP_Accumulate)
print('\n Accumulate using AND Operator :',Accumulate_AND_Operator)
Accumulate_OR_Operator = np.logical_or.accumulate(LOGICAL_OP_Accumulate)
print('\n Accumulate using OR Operator :', Accumulate_OR_Operator)

Accumulate Operation 
 
Accumulate Operation :  [ 1  3  6 10]

 " STRING LIST EXAMPLE "

 String Accumulate :  abcdef

 " LOGICAL OP EXAMPLES "

 Accumulate using AND Operator : [ True  True False]

 Accumulate using OR Operator : [ True  True  True]
